app = "givatayim-library-bot"  # אתה יכול לשנות את השם הזה אם תרצה

[build]
  image = "python:3.11-slim"

[deploy]
  release_command = "pip install -r requirements.txt"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80
